export default {
  TODO_CREATE: 'TODO_CREATE',
  TODO_UPDATE_ITEM: 'TODO_UPDATE_ITEM',
  TODO_SET_FILTER: 'TODO_SET_FILTER',
  TODO_TOGGLE_COMPLETED: 'TODO_TOGGLE_COMPLETED',
  TODO_TOGGLE_COMPLETED_ALL: 'TODO_TOGGLE_COMPLETED_ALL',
  TODO_REMOVE: 'TODO_REMOVE',
  TODO_REMOVE_ALL_COMPLETED: 'TODO_REMOVE_ALL_COMPLETED',

  CHANGE_EVENT: 'change',
  TODO_ID_PREFIX: 'TODO_',
  FILTER_TYPE_ALL: 'all',
  FILTER_TYPE_COMPLETED: 'completed',
  FILTER_TYPE_ACTIVE: 'active'
};